apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idk8s-web
  template:
    metadata:
      labels:
        app: idk8s-web
    spec:
      containers:
      - name: idk8s-web
        imagePullPolicy: Always
        image: ghcr.io/anthonyskentzos/idk8s-web:latest
        ports:
        - containerPort: 80