apiVersion: v1
kind: Service
metadata:
  name: idk8s-web-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: idk8s-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80