apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd  # ArgoCD's namespace
spec:
  destination:
    server: https://kubernetes.default.svc  # Kubernetes API server
    namespace: default  # Namespace where the app-of-apps will be deployed
  source:
    repoURL: https://github.com/anthonyskentzos/k8s-config  # Replace with your Git repository URL
    path: /  # Path to the root of your repository
    targetRevision: HEAD  # or specify a branch/tag/commit
  project: default  # ArgoCD project name

  # Sync policy for the app-of-apps application
  syncPolicy:
    automated:
      prune: true  # Prune resources not specified in Git

  # Application specs for deploying multiple Helm charts
  applications:
    - source:
        repoURL: https://github.com/anthonyskentzos/k8s-config
        path: k8s-app
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: k8s-app  # Namespace for your first Helm chart deployment
      project: default
      chart: k8s-app
      valuesFiles:
        - values-dev.yaml

    - source:
        repoURL: https://github.com/anthonyskentzos/k8s-config
        path: k8s-app-2
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: k8s-app-2  # Namespace for your second Helm chart deployment
      project: default
      chart: k8s-app-2
      valuesFiles:
        - values-dev.yaml

