apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: idk8s-web-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: idk8s.example
    http:
      paths:
      - path: /api/v1/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: idk8s-apiv1-service
            port:
              number: 3000
      - path: /api/v2/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: idk8s-apiv2-service
            port:
              number: 3001
      - path: /doom/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: doom-service
            port:
              number: 3002
      - path: /
        pathType: Prefix
        backend:
          service:
            name: idk8s-web-service
            port:
              number: 80
