---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idk8s-wev-deployment
spec:
  template:
    spec:
      containers:
      - name: idk8s-web
        image: ghcr.io/anthonyskentzos/idk8s-web:latest
