apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: ghcr.io/anthonyskentzos/idk8s-apiv2
- name: ghcr.io/anthonyskentzos/idk8s-web
  newTag: c7d0122
