apiVersion: apps/v1
kind: Deployment
metadata:
  name: idk8s-apiv2-deployment
spec:
  template:
    spec:
      containers:
      - name: idk8s-apiv2
        image: ghcr.io/anthonyskentzos/idk8s-apiv2:latest
