apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiv2-deployment
  namespace: default # Will be overwritten by kustomize overlay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idk8s-apiv2
  template:
    metadata:
      labels:
        app: idk8s-apiv2
    spec:
      containers:
      - name: idk8s-apiv2
        imagePullPolicy: Always
        image: ghcr.io/anthonyskentzos/idk8s-apiv2:748b532
        ports:
        - containerPort: 3001
        livenessProbe:
          httpGet:
            path: /
            port: 3001
        readinessProbe:
          httpGet:
            path: /
            port: 3001
        resources: # TODO: Adjust these with kustomize
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
