apiVersion: v1
kind: Service
metadata:
  name: idk8s-apiv2-service
  namespace: default # Will be overwritten by kustomize overlay
spec:
  type: ClusterIP
  selector:
    app: idk8s-apiv2
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001