apiVersion: v1
kind: Service
metadata:
  name: idk8s-apiv1-service
  namspace: default # Will be overwritten by kustomize overlay
spec:
  type: ClusterIP
  selector:
    app: idk8s-apiv1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000