---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app2-deployment
spec:
  template:
    spec:
      containers:
      - name: k8s-app2
        image: ghcr.io/anthonyskentzos/k8s-app:latest
