apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/ingress.yml  # Include the base Ingress resource

patches:
- path: ingress-patch.yml  # Apply the environment-specific patch
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: idk8s-web-ingress
