apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
# - ../../base

resources:
  - ../../base/ingress.yaml
patches:
  - target:
      kind: Ingress
      name: idk8s-web-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: idk8s.example
