apiVersion: apps/v1
kind: Deployment
metadata:
  name: idk8s-apiv1-deployment
spec:
  template:
    spec:
      containers:
      - name: idk8s-apiv1
        image: ghcr.io/anthonyskentzos/idk8s-apiv1:latest
