---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app2-deployment
  # annotations:
  #   codefresh.io/app: simple-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-app2
  template:
    metadata:
      labels:
        app: k8s-app2
    spec:
      containers:
      - name: k8s-app2
        imagePullPolicy: Always
        image: ghcr.io/anthonyskentzos/k8s-app:latest
        ports:
        - containerPort: 5000
