apiVersion: apps/v1
kind: Deployment
metadata:
  name: doom-deployment
  labels:
    app: doom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doom
  template:
    metadata:
      labels:
        app: doom
    spec:
      containers:
      - name: doom
        image: callumhoughton22/doom-in-docker:0.1
        ports:
        - containerPort: 8080