# Create a deployment for the Doom game server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doom-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doom-app
  template:
    metadata:
      labels:
        app: doom-app
    spec:
      containers:
      - name: doom
        imagePullPolicy: Always
        # image: callumhoughton22/doom-in-docker:0.1
        image: elliottking/doom-wasm:0.1.1
        ports:
        # - containerPort: 8080
          - containerPort: 8000
